services:
  osrs_tracker_frontend:
    image: ghcr.io/redfirebreak/ha-osrs-map-frontend:latest
    environment:
      - HOST_URL=${HOST_URL:-http://osrs_tracker_backend:8080}
      - SITE_TITLE=${SITE_TITLE:-OSRS Guild Map}
      - SITE_NAME=${SITE_NAME:-OSRS Guild Map}
    restart: always
    depends_on:
      - osrs_tracker_backend
    ports:
      - 4000:4000 # change this if you use a reverse proxy such as traefik
  osrs_tracker_backend:
    image: ghcr.io/redfirebreak/ha-osrs-map-backend:latest
    env_file: .env
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:8080 # only needed if something other than the frontend talks to the API directly
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
