name: Update cache

on:
  workflow_dispatch:
  schedule:
    - cron: "51 * * * *"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Checkout runelite
        uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: cache/runelite

      - uses: actions/setup-node@v4

      - run: npm install
        working-directory: ./cache

      - run: npm install
        working-directory: ./site

      - run: npm run update
        working-directory: ./cache

      - name: Commit latest game data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: dump latest game data
