name: Update cache

on:
  workflow_dispatch:
  schedule:
    - cron: "14 * * * *"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout runelite
        uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: cache/runelite

      - uses: actions/setup-node@v4

      - run: npm install
        working-directory: ./cache

      - run: npm install
        working-directory: ./site

      - run: npm run update
        working-directory: ./cache

      - name: Create pull requests
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: dump latest game data
          title: Dump latest game data
          body:
          branch: update-cache
          delete-branch: true
