name: Dump game data

# To run locally: act --env GROUP_IRONMEN_PATH=$PWD -W .github/workflows/update-cache.yml -s GITHUB_TOKEN="$(gh auth token)" -P macos-latest=-self-hosted workflow_dispatch

on:
  workflow_dispatch:
  schedule:
    - cron: 51 * * * *

jobs:
  cache:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: s4u/setup-maven-action@v1.15.0
        with:
          java-version: 11

      - uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT }}'

      - uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: cache/runelite

      - run: npm install
        working-directory: ./cache

      - run: npm install
        working-directory: ./site

      - run: |
          cache=$(curl -s https://archive.openrs2.org/caches.json | jq -r '[.[] | select(.game=="oldschool" and .environment=="live" and .language=="en" and (.sources | contains(["Jagex"])) and .size != null)] | max_by(.id)')
          id=$(echo $cache | jq -r '.id')
          size=$(echo $cache | jq -r '.size')
          echo "CACHE_ID=$id" >> $GITHUB_ENV
          echo "CACHE_SIZE=$size" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        id: cache
        with:
          path: cache/cache
          key: 'cache-${{ env.DATE }}-${{ env.CACHE_ID }}-${{ env.CACHE_SIZE }}'

      - run: curl -o cache/cache/xteas.json https://archive.openrs2.org/caches/runescape/$CACHE_ID/keys.json
        if: steps.cache.outputs.cache-hit != 'true'

      - run: curl -o cache/cache/disk.zip https://archive.openrs2.org/caches/runescape/$CACHE_ID/disk.zip
        if: steps.cache.outputs.cache-hit != 'true'

      - run: unzip cache/cache/disk.zip -d cache/cache
        if: steps.cache.outputs.cache-hit != 'true'

      - run: npm run update
        working-directory: ./cache

      - run: node scripts/quest-scraper.js
        working-directory: ./site

      - run: npm run bundle
        working-directory: ./site

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: '${{ ! env.ACT }}'
        with:
          commit_message: dump latest game data

      - run: rsync -avh --delete --exclude='.git' --exclude='node_modules' . $GROUP_IRONMEN_PATH
        if: '${{ env.ACT }}'
